version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - n 16
      - npm install -g serverless
      - npm install
  # pre_build:
  #   commands:
  #     #put tests here
  #     - npm test
  build:
    commands:
      # NPX used to keep version of serverless
      - npx serverless deploy --stage ${CURRENT_STAGE} --region us-west-2
  post_build:
    commands:
      # - npm run migrate-${CURRENT_STAGE}